version: '3'
services:
  mongo:
    image: mongo:4.0.10
    ports:
      - 27017:27017
#    restart: always
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=admin
#      - MONGO_INITDB_ROOT_PASSWORD=111111
    volumes:
      - ./data:/data
