spring:
  application.name: "culture-code"
  data:
    mongodb:
      host: ${culturecode.db.host:localhost}
      port: ${culturecode.db.port:27017}
      database: ${culturecode.db.database:culture-code}

logging:
  file: "tmp_log.log"
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    app:
      name: "culture-code"
      description: "Universal recommendation system"
      version: "0.0.1"
      encoding: UTF-8