package ru.fmtk.khlystov.culture_code.changelogs.collections

import ru.fmtk.khlystov.culture_code.model.Country

fun getListOfCountries(): Sequence<Country> = sequenceOf(
        Country(null, "Австрийская Республика", "AUT", 40),
        Country(null, "Алжирская Народная Демократическая Республика", "DZA", 12),
        Country(null, "Арабская Республика Египет", "EGY", 818),
        Country(null, "Аргентинская Республика", "ARG", 32),
        Country(null, "Боливарийская Республика Венесуэла", "VEN", 862),
        Country(null, "Британские Виргинские острова", "VGB", 92),
        Country(null, "Великое Герцогство Люксембург", "LUX", 442),
        Country(null, "Венгерская Республика", "HUN", 348),
        Country(null, "Виргинские острова Соединенных Штатов", "VIR", 850),
        Country(null, "Восточная Республика Уругвай", "URY", 858),
        Country(null, "Габонская Республика", "GAB", 266),
        Country(null, "Гвинейская Республика", "GIN", 324),
        Country(null, "Государство Израиль", "ISR", 376),
        Country(null, "Государство Катар", "QAT", 634),
        Country(null, "Государство Кувейт", "KWT", 414),
        Country(null, "Греческая Республика", "GRC", 300),
        Country(null, "Демократическая Республика Конго", "COD", 180),
        Country(null, "Демократическая Республика Сан-Томе и Принсипи", "STP", 678),
        Country(null, "Демократическая Республика Тимор-Лесте", "TLS", 626),
        Country(null, "Демократическая Социалистическая Республика Шри-Ланка", "LKA", 144),
        Country(null, "Иорданское Хашимитское Королевство", "JOR", 400),
        Country(null, "Исламская Республика Иран", "IRN", 364),
        Country(null, "Исламская Республика Мавритания", "MRT", 478),
        Country(null, "Исламская Республика Пакистан", "PAK", 586),
        Country(null, "Итальянская Республика", "ITA", 380),
        Country(null, "Йеменская Республика", "YEM", 887),
        Country(null, "Киргизская Республика", "KGZ", 417),
        Country(null, "Китайская Народная Республика", "CHN", 156),
        Country(null, "Княжество Андорра", "AND", 20),
        Country(null, "Княжество Лихтенштейн", "LIE", 438),
        Country(null, "Княжество Монако", "MCO", 492),
        Country(null, "Корейская Народно-Демократическая Республика", "PRK", 408),
        Country(null, "Королевство Бахрейн", "BHR", 48),
        Country(null, "Королевство Бельгии", "BEL", 56),
        Country(null, "Королевство Бутан", "BTN", 64),
        Country(null, "Королевство Дания", "DNK", 208),
        Country(null, "Королевство Испания", "ESP", 724),
        Country(null, "Королевство Камбоджа", "KHM", 116),
        Country(null, "Королевство Лесото", "LSO", 426),
        Country(null, "Королевство Марокко", "MAR", 504),
        Country(null, "Королевство Непал", "NPL", 524),
        Country(null, "Королевство Нидерландов", "NLD", 528),
        Country(null, "Королевство Норвегия", "NOR", 578),
        Country(null, "Королевство Саудовская Аравия", "SAU", 682),
        Country(null, "Королевство Свазиленд", "SWZ", 748),
        Country(null, "Королевство Таиланд", "THA", 764),
        Country(null, "Королевство Тонга", "TON", 776),
        Country(null, "Королевство Швеция", "SWE", 752),
        Country(null, "Лаосская Народно-Демократическая Республика", "LAO", 418),
        Country(null, "Латвийская Республика", "LVA", 428),
        Country(null, "Ливанская Республика", "LBN", 422),
        Country(null, "Литовская Республика", "LTU", 440),
        Country(null, "Мальдивская Республика", "MDV", 462),
        Country(null, "Мексиканские Соединенные Штаты", "MEX", 484),
        Country(null, "Многонациональное Государство Боливия", "BOL", 68),
        Country(null, "Народная Республика Бангладеш", "BGD", 50),
        Country(null, "Независимое Государство Самоа", "WSM", 882),
        Country(null, "Объединенная Республика Танзания", "TZA", 834),
        Country(null, "Оккупированная Палестинская территория", "PSE", 275),
        Country(null, "Переходное Исламское Государство Афганистан", "AFG", 4),
        Country(null, "Португальская Республика", "PRT", 620),
        Country(null, "Республика Абхазия", "ABH", 895),
        Country(null, "Республика Азербайджан", "AZE", 31),
        Country(null, "Республика Албания", "ALB", 8),
        Country(null, "Республика Ангола", "AGO", 24),
        Country(null, "Республика Армения", "ARM", 51),
        Country(null, "Республика Беларусь", "BLR", 112),
        Country(null, "Республика Бенин", "BEN", 204),
        Country(null, "Республика Болгария", "BGR", 100),
        Country(null, "Республика Ботсвана", "BWA", 72),
        Country(null, "Республика Бурунди", "BDI", 108),
        Country(null, "Республика Вануату", "VUT", 548),
        Country(null, "Республика Гаити", "HTI", 332),
        Country(null, "Республика Гайана", "GUY", 328),
        Country(null, "Республика Гамбия", "GMB", 270),
        Country(null, "Республика Гана", "GHA", 288),
        Country(null, "Республика Гватемала", "GTM", 320),
        Country(null, "Республика Гвинея-Бисау", "GNB", 624),
        Country(null, "Республика Гондурас", "HND", 340),
        Country(null, "Республика Джибути", "DJI", 262),
        Country(null, "Республика Замбия", "ZMB", 894),
        Country(null, "Республика Зимбабве", "ZWE", 716),
        Country(null, "Республика Индия", "IND", 356),
        Country(null, "Республика Индонезия", "IDN", 360),
        Country(null, "Республика Ирак", "IRQ", 368),
        Country(null, "Республика Исландия", "ISL", 352),
        Country(null, "Республика Кабо-Верде", "CPV", 132),
        Country(null, "Республика Казахстан", "KAZ", 398),
        Country(null, "Республика Камерун", "CMR", 120),
        Country(null, "Республика Кения", "KEN", 404),
        Country(null, "Республика Кипр", "CYP", 196),
        Country(null, "Республика Кирибати", "KIR", 296),
        Country(null, "Республика Колумбия", "COL", 170),
        Country(null, "Республика Конго", "COG", 178),
        Country(null, "Республика Корея", "KOR", 410),
        Country(null, "Республика Коста-Рика", "CRI", 188),
        Country(null, "Республика Кот д'Ивуар", "CIV", 384),
        Country(null, "Республика Куба", "CUB", 192),
        Country(null, "Республика Либерия", "LBR", 430),
        Country(null, "Республика Маврикий", "MUS", 480),
        Country(null, "Республика Мадагаскар", "MDG", 450),
        Country(null, "Республика Малави", "MWI", 454),
        Country(null, "Республика Мали", "MLI", 466),
        Country(null, "Республика Мальта", "MLT", 470),
        Country(null, "Республика Маршалловы острова", "MHL", 584),
        Country(null, "Республика Мозамбик", "MOZ", 508),
        Country(null, "Республика Молдова", "MDA", 498),
        Country(null, "Республика Намибия", "NAM", 516),
        Country(null, "Республика Науру", "NRU", 520),
        Country(null, "Республика Нигер", "NER", 562),
        Country(null, "Республика Никарагуа", "NIC", 558),
        Country(null, "Республика Ниуэ", "NIU", 570),
        Country(null, "Республика островов Фиджи", "FJI", 242),
        Country(null, "Республика Палау", "PLW", 585),
        Country(null, "Республика Панама", "PAN", 591),
        Country(null, "Республика Парагвай", "PRY", 600),
        Country(null, "Республика Перу", "PER", 604),
        Country(null, "Республика Польша", "POL", 616),
        Country(null, "Республика Сан-Марино", "SMR", 674),
        Country(null, "Республика Сейшелы", "SYC", 690),
        Country(null, "Республика Сенегал", "SEN", 686),
        Country(null, "Республика Сербия", "SRB", 688),
        Country(null, "Республика Сингапур", "SGP", 702),
        Country(null, "Республика Словения", "SVN", 705),
        Country(null, "Республика Судан", "SDN", 729),
        Country(null, "Республика Суринам", "SUR", 740),
        Country(null, "Республика Сьерра-Леоне", "SLE", 694),
        Country(null, "Республика Таджикистан", "TJK", 762),
        Country(null, "Республика Тринидад и Тобаго", "TTO", 780),
        Country(null, "Республика Уганда", "UGA", 800),
        Country(null, "Республика Узбекистан", "UZB", 860),
        Country(null, "Республика Филиппины", "PHL", 608),
        Country(null, "Республика Хорватия", "HRV", 191),
        Country(null, "Республика Чад", "TCD", 148),
        Country(null, "Республика Черногория", "MNE", 499),
        Country(null, "Республика Чили", "CHL", 152),
        Country(null, "Республика Эквадор", "ECU", 218),
        Country(null, "Республика Экваториальная Гвинея", "GNQ", 226),
        Country(null, "Республика Эль-Сальвадор", "SLV", 222),
        Country(null, "Республика Южная Осетия", "OST", 896),
        Country(null, "Российская Федерация", "RUS", 643),
        Country(null, "Руандийская Республика", "RWA", 646),
        Country(null, "Словацкая Республика", "SVK", 703),
        Country(null, "Содружество Багамы", "BHS", 44),
        Country(null, "Содружество Доминики", "DMA", 212),
        Country(null, "Содружество Северных Марианских островов", "MNP", 580),
        Country(null, "Соединенное Королевство Великобритании и Северной Ирландии", "GBR", 826),
        Country(null, "Соединенные Штаты Америки", "USA", 840),
        Country(null, "Сомалийская Республика", "SOM", 706),
        Country(null, "Социалистическая Народная Ливийская Арабская Джамахирия", "LBY", 434),
        Country(null, "Социалистическая Республика Вьетнам", "VNM", 704),
        Country(null, "Союз Коморы", "COM", 174),
        Country(null, "Союз Мьянма", "MMR", 104),
        Country(null, "Специальный  административный  регион Китая Гонконг", "HKG", 344),
        Country(null, "Специальный административный регион Китая Макао", "MAC", 446),
        Country(null, "Султанат Оман", "OMN", 512),
        Country(null, "Тоголезская Республика", "TGO", 768),
        Country(null, "Тунисская Республика", "TUN", 788),
        Country(null, "Турецкая Республика", "TUR", 792),
        Country(null, "Туркменистан", "TKM", 795),
        Country(null, "Федеративная Демократическая Республика Эфиопия", "ETH", 231),
        Country(null, "Федеративная Республика Бразилия", "BRA", 76),
        Country(null, "Федеративная Республика Германия", "DEU", 276),
        Country(null, "Федеративная Республика Нигерия", "NGA", 566),
        Country(null, "Федеративные штаты Микронезии", "FSM", 583),
        Country(null, "Финляндская Республика", "FIN", 246),
        Country(null, "Французская Республика", "FRA", 250),
        Country(null, "Швейцарская Конфедерация", "CHE", 756),
        Country(null, "Эстонская Республика", "EST", 233),
        Country(null, "Южно-Африканская Республика", "ZAF", 710)
)